# Generated by Django 2.0.7 on 2018-07-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Hostel_Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('label', models.CharField(max_length=200)),
                ('priority', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Near_by',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('near_by_place', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='nearby_hotels',
            field=models.ManyToManyField(to='list.Near_by'),
        ),
    ]
