# Generated by Django 2.0.7 on 2018-07-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='nearby_hotels',
            field=models.ManyToManyField(blank=True, to='list.Near_by'),
        ),
    ]
