# Generated by Django 2.0.7 on 2018-07-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20180716_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='contact',
            field=models.IntegerField(default=1),
        ),
    ]
