# Generated by Django 2.0.7 on 2018-07-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_list_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='contact',
            field=models.IntegerField(default=0),
        ),
    ]
