# Generated by Django 2.0.7 on 2018-07-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20180717_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='near_by',
            name='distance',
            field=models.IntegerField(default=0),
        ),
    ]
