# Generated by Django 2.0.7 on 2018-07-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_remove_near_by_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='Adress',
            field=models.TextField(default='NULL'),
            preserve_default=False,
        ),
    ]
